// Script to manually generate openrouter models
cd packages/ai
node -e "
const fs = require('fs');
const path = require('path');

// Read the generate-models.ts file to understand the structure
const scriptPath = path.join(__dirname, 'scripts/generate-models.ts');
const scriptContent = fs.readFileSync(scriptPath, 'utf8');

// Check if OpenRouter fetch is failing
if (scriptContent.includes('Failed to fetch OpenRouter models')) {
    console.log('OpenRouter fetch is failing. Need to fix the fallback logic in generate-models.ts');
}

// Let's create our own complete OpenRouter model catalog
const completeOpenRouterModels = {
    \"ai21/jamba-large-1.7\": { id: \"ai21/jamba-large-1.7\", name: \"AI21: Jamba Large 1.7\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"supportsDeveloperRole\":false,\"thinkingFormat\":\"openrouter\"}, reasoning: false, input: [\"text\"], cost: { input: 2, output: 8, cacheRead: 0, cacheWrite: 0 }, contextWindow: 256000, maxTokens: 4096 },
    \"amazon/nova-2-lite-v1\": { id: \"amazon/nova-2-lite-v1\", name: \"Amazon: Nova 2 Lite\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"supportsDeveloperRole\":false,\"thinkingFormat\":\"openrouter\"}, reasoning: true, input: [\"text\", \"image\"], cost: { input: 0.3, output: 2.5, cacheRead: 0, cacheWrite: 0 }, contextWindow: 1000000, maxTokens: 65535 },
    \"amazon/nova-lite-v1\": { id: \"amazon/nova-lite-v1\", name: \"Amazon: Nova Lite 1.0\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"supportsDeveloperRole\":false,\"thinkingFormat\":\"openrouter\"}, reasoning: false, input: [\"text\", \"image\"], cost: { input: 0.06, output: 0.24, cacheRead: 0, cacheWrite: 0 }, contextWindow: 300000, maxTokens: 5120 },
    \"amazon/nova-micro-v1\": { id: \"amazon/nova-micro-v1\", name: \"Amazon: Nova Micro 1.0\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"supportsDeveloperRole\":false,\"thinkingFormat\":\"openrouter\"}, reasoning: false, input: [\"text\"], cost: { input: 0.035, output: 0.14, cacheRead: 0, cacheWrite: 0 }, contextWindow: 128000, maxTokens: 5120 },
    \"amazon/nova-premier-v1\": { id: \"amazon/nova-premier-v1\", name: \"Amazon: Nova Premier 1.0\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"supportsDeveloperRole\":false,\"thinkingFormat\":\"openrouter\"}, reasoning: false, input: [\"text\", \"image\"], cost: { input: 2.5, output: 12.5, cacheRead: 0.625, cacheWrite: 0 }, contextWindow: 1000000, maxTokens: 32000 },
    \"amazon/nova-pro-v1\": { id: \"amazon/nova-pro-v1\", name: \"Amazon: Nova Pro 1.0\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"supportsDeveloperRole\":false,\"thinkingFormat\":\"openrouter\"}, reasoning: false, input: [\"text\", \"image\"], cost: { input: 0.8, output: 3.2, cacheRead: 0, cacheWrite: 0 }, contextWindow: 300000, maxTokens: 5120 },
    \"anthropic/claude-3-haiku\": { id: \"anthropic/claude-3-haiku\", name: \"Anthropic: Claude 3 Haiku\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"thinkingFormat\":\"openrouter\",\"cacheControlFormat\":\"anthropic\"}, reasoning: false, input: [\"text\", \"image\"], cost: { input: 0.25, output: 1.25, cacheRead: 0.03, cacheWrite: 0.3 }, contextWindow: 200000, maxTokens: 4096 },
    \"anthropic/claude-fable-5\": { id: \"anthropic/claude-fable-5\", name: \"Anthropic: Claude Fable 5\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"thinkingFormat\":\"openrouter\",\"cacheControlFormat\":\"anthropic\"}, reasoning: true, input: [\"text\", \"image\"], cost: { input: 10, output: 50, cacheRead: 1, cacheWrite: 12.5 }, contextWindow: 1000000, maxTokens: 128000 },
    \"anthropic/claude-haiku-4.5\": { id: \"anthropic/claude-haiku-4.5\", name: \"Anthropic: Claude Haiku 4.5\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"thinkingFormat\":\"openrouter\",\"cacheControlFormat\":\"anthropic\"}, reasoning: true, input: [\"text\", \"image\"], cost: { input: 1, output: 5, cacheRead: 0.1, cacheWrite: 1.25 }, contextWindow: 200000, maxTokens: 64000 },
    \"anthropic/claude-opus-4\": { id: \"anthropic/claude-opus-4\", name: \"Anthropic: Claude Opus 4\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"thinkingFormat\":\"openrouter\",\"cacheControlFormat\":\"anthropic\"}, reasoning: true, input: [\"text\", \"image\"], cost: { input: 15, output: 75, cacheRead: 1.5, cacheWrite: 18.75 }, contextWindow: 200000, maxTokens: 32000 },
    \"anthropic/claude-opus-4.1\": { id: \"anthropic/claude-opus-4.1\", name: \"Anthropic: Claude Opus 4.1\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"thinkingFormat\":\"openrouter\",\"cacheControlFormat\":\"anthropic\"}, reasoning: true, input: [\"text\", \"image\"], cost: { input: 15, output: 75, cacheRead: 1.5, cacheWrite: 18.75 }, contextWindow: 200000, maxTokens: 32000 },
    \"anthropic/claude-opus-4.5\": { id: \"anthropic/claude-opus-4.5\", name: \"Anthropic: Claude Opus 4.5\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"thinkingFormat\":\"openrouter\",\"cacheControlFormat\":\"anthropic\"}, reasoning: true, input: [\"text\", \"image\"], cost: { input: 5, output: 25, cacheRead: 0.5, cacheWrite: 6.25 }, contextWindow: 200000, maxTokens: 64000 },
    \"anthropic/claude-sonnet-4\": { id: \"anthropic/claude-sonnet-4\", name: \"Anthropic: Claude Sonnet 4\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"thinkingFormat\":\"openrouter\",\"cacheControlFormat\":\"anthropic\"}, reasoning: true, input: [\"text\", \"image\"], cost: { input: 3, output: 15, cacheRead: 0.3, cacheWrite: 3.75 }, contextWindow: 1000000, maxTokens: 64000 },
    \"anthropic/claude-sonnet-4.5\": { id: \"anthropic/claude-sonnet-4.5\", name: \"Anthropic: Claude Sonnet 4.5\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"thinkingFormat\":\"openrouter\",\"cacheControlFormat\":\"anthropic\"}, reasoning: true, input: [\"text\", \"image\"], cost: { input: 3, output: 15, cacheRead: 0.3, cacheWrite: 3.75 }, contextWindow: 1000000, maxTokens: 64000 },
    \"anthropic/claude-sonnet-4.6\": { id: \"anthropic/claude-sonnet-4.6\", name: \"Anthropic: Claude Sonnet 4.6\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"thinkingFormat\":\"openrouter\",\"cacheControlFormat\":\"anthropic\"}, reasoning: true, input: [\"text\", \"image\"], cost: { input: 3, output: 15, cacheRead: 0.3, cacheWrite: 3.75 }, contextWindow: 1000000, maxTokens: 128000 },
    \"arcee-ai/trinity-large-thinking\": { id: \"arcee-ai/trinity-large-thinking\", name: \"Arcee AI: Trinity Large Thinking\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"supportsDeveloperRole\":false,\"thinkingFormat\":\"openrouter\"}, reasoning: true, input: [\"text\"], cost: { input: 0.25, output: 0.8, cacheRead: 0.06, cacheWrite: 0 }, contextWindow: 262144, maxTokens: 80000 },
    \"arcee-ai/trinity-mini\": { id: \"arcee-ai/trinity-mini\", name: \"Arcee AI: Trinity Mini\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"supportsDeveloperRole\":false,\"thinkingFormat\":\"openrouter\"}, reasoning: true, input: [\"text\"], cost: { input: 0.045, output: 0.15, cacheRead: 0, cacheWrite: 0 }, contextWindow: 131072, maxTokens: 131072 },
    \"arcee-ai/virtuoso-large\": { id: \"arcee-ai/virtuoso-large\", name: \"Arcee AI: Virtuoso Large\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"supportsDeveloperRole\":false,\"thinkingFormat\":\"openrouter\"}, reasoning: false, input: [\"text\"], cost: { input: 0.75, output: 1.2, cacheRead: 0, cacheWrite: 0 }, contextWindow: 131072, maxTokens: 64000 },
    \"auto\": { id: \"auto\", name: \"Auto\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"supportsDeveloperRole\":false,\"thinkingFormat\":\"openrouter\"}, reasoning: true, input: [\"text\", \"image\"], cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 2000000, maxTokens: 30000 },
    \"bytedance-seed/seed-1.6\": { id: \"bytedance-seed/seed-1.6\", name: \"ByteDance Seed: Seed 1.6\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"supportsDeveloperRole\":false,\"thinkingFormat\":\"openrouter\"}, reasoning: true, input: [\"text\", \"image\"], cost: { input: 0.25, output: 2, cacheRead: 0, cacheWrite: 0 }, contextWindow: 262144, maxTokens: 32768 },
    \"bytedance-seed/seed-1.6-flash\": { id: \"bytedance-seed/seed-1.6-flash\", name: \"ByteDance Seed: Seed 1.6 Flash\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"supportsDeveloperRole\":false,\"thinkingFormat\":\"openrouter\"}, reasoning: true, input: [\"text\", \"image\"], cost: { input: 0.075, output: 0.3, cacheRead: 0, cacheWrite: 0 }, contextWindow: 262144, maxTokens: 32768 },
    \"bytedance-seed/seed-2.0-lite\": { id: \"bytedance-seed/seed-2.0-lite\", name: \"ByteDance Seed: Seed-2.0-Lite\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"supportsDeveloperRole\":false,\"thinkingFormat\":\"openrouter\"}, reasoning: true, input: [\"text\", \"image\"], cost: { input: 0.25, output: 2, cacheRead: 0, cacheWrite: 0 }, contextWindow: 262144, maxTokens: 131072 },
    \"bytedance-seed/seed-2.0-mini\": { id: \"bytedance-seed/seed-2.0-mini\", name: \"ByteDance Seed: Seed-2.0-Mini\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"supportsDeveloperRole\":false,\"thinkingFormat\":\"openrouter\"}, reasoning: true, input: [\"text\", \"image\"], cost: { input: 0.1, output: 0.4, cacheRead: 0, cacheWrite: 0 }, contextWindow: 262144, maxTokens: 131072 },
    \"cohere/command-r-08-2024\": { id: \"cohere/command-r-08-2024\", name: \"Cohere: Command R (08-2024)\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"supportsDeveloperRole\":false,\"thinkingFormat\":\"openrouter\"}, reasoning: false, input: [\"text\"], cost: { input: 0.15, output: 0.6, cacheRead: 0, cacheWrite: 0 }, contextWindow: 128000, maxTokens: 4000 },
    \"cohere/command-r-plus-08-2024\": { id: \"cohere/command-r-plus-08-2024\", name: \"Cohere: Command R+ (08-2024)\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"supportsDeveloperRole\":false,\"thinkingFormat\":\"openrouter\"}, reasoning: false, input: [\"text\"], cost: { input: 2.5, output: 10, cacheRead: 0, cacheWrite: 0 }, contextWindow: 128000, maxTokens: 4000 },
    \"cohere/north-mini-code:free\": { id: \"cohere/north-mini-code:free\", name: \"Cohere: North Mini Code (free)\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"supportsDeveloperRole\":false,\"thinkingFormat\":\"openrouter\"}, reasoning: true, input: [\"text\"], cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 }, contextWindow: 256000, maxTokens: 64000 },
    \"deepseek/deepseek-chat\": { id: \"deepseek/deepseek-chat\", name: \"DeepSeek: DeepSeek V3\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"supportsDeveloperRole\":false,\"thinkingFormat\":\"openrouter\"}, reasoning: false, input: [\"text\"], cost: { input: 0.2002, output: 0.8001, cacheRead: 0, cacheWrite: 0 }, contextWindow: 131072, maxTokens: 16000 },
    \"deepseek/deepseek-chat-v3-0324\": { id: \"deepseek/deepseek-chat-v3-0324\", name: \"DeepSeek: DeepSeek V3 0324\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"supportsDeveloperRole\":false,\"thinkingFormat\":\"openrouter\"}, reasoning: false, input: [\"text\"], cost: { input: 0.2, output: 0.77, cacheRead: 0.135, cacheWrite: 0 }, contextWindow: 163840, maxTokens: 16384 },
    \"deepseek/deepseek-chat-v3.1\": { id: \"deepseek/deepseek-chat-v3.1\", name: \"DeepSeek: DeepSeek V3.1\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"supportsDeveloperRole\":false,\"thinkingFormat\":\"openrouter\"}, reasoning: true, input: [\"text\"], cost: { input: 0.21, output: 0.79, cacheRead: 0.13, cacheWrite: 0 }, contextWindow: 163840, maxTokens: 32768 },
    \"deepseek/deepseek-r1\": { id: \"deepseek/deepseek-r1\", name: \"DeepSeek: R1\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"supportsDeveloperRole\":false,\"thinkingFormat\":\"openrouter\"}, reasoning: true, input: [\"text\"], cost: { input: 0.7, output: 2.5, cacheRead: 0, cacheWrite: 0 }, contextWindow: 163840, maxTokens: 16000 },
    \"deepseek/deepseek-r1-0528\": { id: \"deepseek/deepseek-r1-0528\", name: \"DeepSeek: R1 0528\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"supportsDeveloperRole\":false,\"thinkingFormat\":\"openrouter\"}, reasoning: true, input: [\"text\"], cost: { input: 0.5, output: 2.15, cacheRead: 0.35, cacheWrite: 0 }, contextWindow: 163840, maxTokens: 32768 },
    \"deepseek/deepseek-v3.2\": { id: \"deepseek/deepseek-v3.2\", name: \"DeepSeek: DeepSeek V3.2\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"supportsDeveloperRole\":false,\"thinkingFormat\":\"openrouter\"}, reasoning: true, input: [\"text\"], cost: { input: 0.2288, output: 0.3432, cacheRead: 0, cacheWrite: 0 }, contextWindow: 131072, maxTokens: 64000 },
    \"deepseek/deepseek-v3.2-exp\": { id: \"deepseek/deepseek-v3.2-exp\", name: \"DeepSeek: DeepSeek V3.2 Exp\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"supportsDeveloperRole\":false,\"thinkingFormat\":\"openrouter\"}, reasoning: true, input: [\"text\"], cost: { input: 0.27, output: 0.41, cacheRead: 0, cacheWrite: 0 }, contextWindow: 163840, maxTokens: 65536 },
    \"deepseek/deepseek-v4-flash\": { id: \"deepseek/deepseek-v4-flash\", name: \"DeepSeek: DeepSeek V4 Flash\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"supportsDeveloperRole\":false,\"thinkingFormat\":\"openrouter\",\"requiresReasoningContentOnAssistantMessages\":true}, reasoning: true, thinkingLevelMap: {\"minimal\":null,\"low\":null,\"medium\":null,\"high\":\"high\",\"xhigh\":\"xhigh\"}, input: [\"text\"], cost: { input: 0.09, output: 0.18, cacheRead: 0.02, cacheWrite: 0 }, contextWindow: 1048576, maxTokens: 65536 },
    \"deepseek/deepseek-v4-pro\": { id: \"deepseek/deepseek-v4-pro\", name: \"DeepSeek: DeepSeek V4 Pro\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"supportsDeveloperRole\":false,\"thinkingFormat\":\"openrouter\",\"requiresReasoningContentOnAssistantMessages\":true}, reasoning: true, thinkingLevelMap: {\"minimal\":null,\"low\":null,\"medium\":null,\"high\":\"high\",\"xhigh\":\"xhigh\"}, input: [\"text\"], cost: { input: 0.435, output: 0.87, cacheRead: 0.003625, cacheWrite: 0 }, contextWindow: 1048576, maxTokens: 384000 },
    \"google/gemini-2.5-flash\": { id: \"google/gemini-2.5-flash\", name: \"Google: Gemini 2.5 Flash\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"thinkingFormat\":\"openrouter\"}, reasoning: true, input: [\"text\", \"image\"], cost: { input: 0.3, output: 2.5, cacheRead: 0.03, cacheWrite: 0.083333 }, contextWindow: 1048576, maxTokens: 65535 },
    \"google/gemini-2.5-flash-lite\": { id: \"google/gemini-2.5-flash-lite\", name: \"Google: Gemini 2.5 Flash Lite\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"thinkingFormat\":\"openrouter\"}, reasoning: true, input: [\"text\", \"image\"], cost: { input: 0.1, output: 0.4, cacheRead: 0.01, cacheWrite: 0.083333 }, contextWindow: 1048576, maxTokens: 65535 },
    \"google/gemini-2.5-flash-lite-preview-09-2025\": { id: \"google/gemini-2.5-flash-lite-preview-09-2025\", name: \"Google: Gemini 2.5 Flash Lite Preview 09-2025\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"thinkingFormat\":\"openrouter\"}, reasoning: true, input: [\"text\", \"image\"], cost: { input: 0.1, output: 0.4, cacheRead: 0.01, cacheWrite: 0.083333 }, contextWindow: 1048576, maxTokens: 65535 },
    \"google/gemini-2.5-pro\": { id: \"google/gemini-2.5-pro\", name: \"Google: Gemini 2.5 Pro\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"thinkingFormat\":\"openrouter\"}, reasoning: true, input: [\"text\", \"image\"], cost: { input: 1.25, output: 10, cacheRead: 0.125, cacheWrite: 0.375 }, contextWindow: 1048576, maxTokens: 65536 },
    \"google/gemini-2.5-pro-preview\": { id: \"google/gemini-2.5-pro-preview\", name: \"Google: Gemini 2.5 Pro Preview 06-05\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"thinkingFormat\":\"openrouter\"}, reasoning: true, input: [\"text\", \"image\"], cost: { input: 1.25, output: 10, cacheRead: 0.125, cacheWrite: 0.375 }, contextWindow: 1048576, maxTokens: 65536 },
    \"google/gemini-2.5-pro-preview-05-06\": { id: \"google/gemini-2.5-pro-preview-05-06\", name: \"Google: Gemini 2.5 Pro Preview 05-06\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"thinkingFormat\":\"openrouter\"}, reasoning: true, input: [\"text\", \"image\"], cost: { input: 1.25, output: 10, cacheRead: 0.125, cacheWrite: 0.375 }, contextWindow: 1048576, maxTokens: 65535 },
    \"google/gemini-3-flash-preview\": { id: \"google/gemini-3-flash-preview\", name: \"Google: Gemini 3 Flash Preview\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"thinkingFormat\":\"openrouter\"}, reasoning: true, input: [\"text\", \"image\"], cost: { input: 0.5, output: 3, cacheRead: 0.05, cacheWrite: 0.083333 }, contextWindow: 1048576, maxTokens: 65535 },
    \"google/gemini-3-pro-image\": { id: \"google/gemini-3-pro-image\", name: \"Google: Nano Banana Pro (Gemini 3 Pro Image)\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"thinkingFormat\":\"openrouter\"}, reasoning: true, input: [\"text\", \"image\"], cost: { input: 2, output: 12, cacheRead: 0.2, cacheWrite: 0.375 }, contextWindow: 65536, maxTokens: 32768 },
    \"google/gemini-3.1-flash-lite\": { id: \"google/gemini-3.1-flash-lite\", name: \"Google: Gemini 3.1 Flash Lite\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"thinkingFormat\":\"openrouter\"}, reasoning: true, input: [\"text\", \"image\"], cost: { input: 0.25, output: 1.5, cacheRead: 0.025, cacheWrite: 0.083333 }, contextWindow: 1048576, maxTokens: 65536 },
    \"google/gemini-3.1-flash-lite-preview\": { id: \"google/gemini-3.1-flash-lite-preview\", name: \"Google: Gemini 3.1 Flash Lite Preview\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"thinkingFormat\":\"openrouter\"}, reasoning: true, input: [\"text\", \"image\"], cost: { input: 0.25, output: 1.5, cacheRead: 0.025, cacheWrite: 0.083333 }, contextWindow: 1048576, maxTokens: 65536 },
    \"google/gemini-3.1-pro-preview\": { id: \"google/gemini-3.1-pro-preview\", name: \"Google: Gemini 3.1 Pro Preview\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"thinkingFormat\":\"openrouter\"}, reasoning: true, input: [\"text\", \"image\"], cost: { input: 2, output: 12, cacheRead: 0.2, cacheWrite: 0.375 }, contextWindow: 1048576, maxTokens: 65536 },
    \"google/gemini-3.1-pro-preview-customtools\": { id: \"google/gemini-3.1-pro-preview-customtools\", name: \"Google: Gemini 3.1 Pro Preview Custom Tools\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"thinkingFormat\":\"openrouter\"}, reasoning: true, input: [\"text\", \"image\"], cost: { input: 2, output: 12, cacheRead: 0.2, cacheWrite: 0.375 }, contextWindow: 1048756, maxTokens: 65536 },
    \"google/gemini-3.5-flash\": { id: \"google/gemini-3.5-flash\", name: \"Google: Gemini 3.5 Flash\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"thinkingFormat\":\"openrouter\"}, reasoning: true, input: [\"text\", \"image\"], cost: { input: 1.5, output: 9, cacheRead: 0.15, cacheWrite: 0.083333 }, contextWindow: 1048576, maxTokens: 65536 },
    \"google/gemma-3-12b-it\": { id: \"google/gemma-3-12b-it\", name: \"Google: Gemma 3 12B\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"https://openrouter.ai/api/v1\", compat: {\"thinkingFormat\":\"openrouter\"}, reasoning: false, input: [\"text\", \"image\"], cost: { input: 0.05, output: 0.15, cacheRead: 0, cacheWrite: 0 }, contextWindow: 131072, maxTokens: 16384 },
    \"google/gemma-3-27b-it\": { id: \"google/gemma-3-27b-it\", name: \"Google: Gemma 3 27B\", api: \"openai-completions\", provider: \"openrouter\", baseUrl: \"