// Write a script to fix openrouter models

const fs = require('fs');
const path = require('path');

// Read the generated openrouter models file
const openrouterModelsPath = path.join(__dirname, 'src/providers/openrouter.models.ts');
const openrouterContent = fs.readFileSync(openrouterModelsPath, 'utf8');

// Check what's in the file
console.log('Current openrouter.models.ts length:', openrouterContent.length);
console.log('First 500 chars:', openrouterContent.substring(0, 500));

// The file should contain models like anthropic/claude-sonnet-4, deepseek/deepseek-v3.2, etc.
// but it seems to only have auto and fusion router models.

// Let's create a fix by regenerating with proper fallback

const scriptPath = path.join(__dirname, 'scripts/generate-models.ts');
const scriptContent = fs.readFileSync(scriptPath, 'utf8');

// Check if our fallback logic is in place
if (scriptContent.includes("Using fallback OpenRouter models")) {
    console.log('✓ Fallback logic found in generate-models.ts');
} else {
    console.log('✗ Fallback logic NOT found in generate-models.ts');
}

// Let's manually fix the openrouter.models.ts by adding back the missing models
const baseContent = `// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import type { Model } from "../types.ts";

export const OPENROUTER_MODELS = {\n`;

const routerModels = {
    "anthropic/claude-sonnet-4": {
        id: "anthropic/claude-sonnet-4",
        name: "Anthropic: Claude Sonnet 4",
        api: "openai-completions",
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        compat: {"thinkingFormat":"openrouter","cacheControlFormat":"anthropic"},
        reasoning: true,
        input: ["text", "image"],
        cost: { input: 3, output: 15, cacheRead: 0.3, cacheWrite: 3.75 },
        contextWindow: 1000000,
        maxTokens: 64000,
    },
    "deepseek/deepseek-v3.2": {
        id: "deepseek/deepseek-v3.2",
        name: "DeepSeek: DeepSeek V3.2",
        api: "openai-completions",
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        compat: {"thinkingFormat":"openrouter"},
        reasoning: true,
        input: ["text"],
        cost: { input: 0.2288, output: 0.3432, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 131072,
        maxTokens: 64000,
    },
    "mistralai/mistral-large-2512": {
        id: "mistralai/mistral-large-2512",
        name: "Mistral: Mistral Large 3 2512",
        api: "openai-completions",
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        compat: {"thinkingFormat":"openrouter"},
        reasoning: false,
        input: ["text", "image"],
        cost: { input: 0.5, output: 1.5, cacheRead: 0.05, cacheWrite: 0 },
        contextWindow: 262144,
        maxTokens: 4096,
    },
    "google/gemini-2.5-flash": {
        id: "google/gemini-2.5-flash",
        name: "Google: Gemini 2.5 Flash",
        api: "openai-completions",
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        compat: {"thinkingFormat":"openrouter"},
        reasoning: true,
        input: ["text", "image"],
        cost: { input: 0.3, output: 2.5, cacheRead: 0.03, cacheWrite: 0.083333 },
        contextWindow: 1048576,
        maxTokens: 65535,
    },
    "meta-llama/llama-4-scout": {
        id: "meta-llama/llama-4-scout",
        name: "Meta: Llama 4 Scout",
        api: "openai-completions",
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        compat: {"thinkingFormat":"openrouter"},
        reasoning: false,
        input: ["text", "image"],
        cost: { input: 0.1, output: 0.3, cacheRead: 0, cacheWrite: 0 },
        contextWindow: 10000000,
        maxTokens: 16384,
    }
};

// Generate the full content
let fullContent = baseContent;
let count = 0;

for (const [key, model] of Object.entries(routerModels)) {
    fullContent += `\t\"${key}\": {\n`;
    fullContent += `\t\tid: \"${model.id}\",\n`;
    fullContent += `\t\tname: \"${model.name}\",\n`;
    fullContent += `\t\tapi: \"${model.api}\",\n`;
    fullContent += `\t\tprovider: \"${model.provider}\",\n`;
    fullContent += `\t\tbaseUrl: \"${model.baseUrl}\",\n`;
    fullContent += `\t\tcompat: ${JSON.stringify(model.compat)},\n`;
    fullContent += `\t\treasoning: ${model.reasoning},\n`;
    fullContent += `\t\tinput: [${model.input.map(i => `\"${i}\"`).join(\", \")}],\n`;
    fullContent += `\t\tcost: {\n`;
    fullContent += `\t\t\tinput: ${model.cost.input},\n`;
    fullContent += `\t\t\toutput: ${model.cost.output},\n`;
    fullContent += `\t\t\tcacheRead: ${model.cost.cacheRead},\n`;
    fullContent += `\t\t\tcacheWrite: ${model.cost.cacheWrite},\n`;
    fullContent += `\t\t},\n`;
    fullContent += `\t\tcontextWindow: ${model.contextWindow},\n`;
    fullContent += `\t\tmaxTokens: ${model.maxTokens},\n`;
    fullContent += `\t} satisfies Model<\"openai-completions\">,\n`;
    count++;
}

fullContent += `} as const;\n`;

// Write to temp file
const tempPath = path.join(__dirname, 'src/providers/openrouter.models.ts.temp');
fs.writeFileSync(tempPath, fullContent);

console.log(`Generated ${count} models in temp file`);
console.log('Check:', tempPath);